[project]
name = "flash_attention_triton"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "jinho-choi123", email = "choijinho817@gmail.com" }
]
requires-python = ">=3.12,<3.15"
dependencies = []

[project.scripts]
flash-attention-triton = "flash_attention_triton:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
