[project]
name = "gpu_toys"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "jinho-choi123", email = "choijinho817@gmail.com" }
]
requires-python = ">=3.13,<3.14"
dependencies = [
    "flash_attention_1_triton",
    "loguru==0.7.3",
    "nvidia-cutlass-dsl==4.6.1",
    "nvidia-nvshmem-cu12==3.4.5",
    "nvshmem4py-cu12==0.3.1",
    "torch==2.11.0",
]

[dependency-groups]
dev = [
    "cmake==3.26.0",
    "ninja==1.13.0",
    "pybind11==3.0.4",
    "pre-commit==4.6.0",
    "pytest==9.0.3",
    "pytest-env>=1.7.0",
    "ruff==0.15.14",
    "ty==0.0.38",
]

[tool.uv]
default-groups = ["dev"]
environments = ["sys_platform == 'linux'"]

[tool.uv.workspace]
members = [
    "flash_attention_1_triton",
]

[tool.uv.sources]
"flash_attention_1_triton" = {workspace=true}
torch = [
    { index = "pytorch-cu129", marker = "sys_platform == 'linux'" },
]

[[tool.uv.index]]
name = "pytorch-cu129"
url = "https://download.pytorch.org/whl/cu129"
explicit = true

[pytest_env]
CUDA_VISIBLE_DEVICES="0"

[tool.ruff]
line-length = 100
target-version = "py313"
extend-exclude = ["docs"]

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "SIM", "T201", "D"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"

[tool.ty.environment]
python = ".venv"
python-version = "3.13"
root = ["."]
extra-paths = [
    ".venv/lib/python3.13/site-packages/nvidia_cutlass_dsl/dsl_packages",
]

[tool.ty.src]
include = ["flash_attention_1_triton", "scripts"]
exclude = ["docs/"]
