[project]
name = "flash_attention_1_triton"
version = "0.1.0"
description = "A Triton implementation of FlashAttention 1"
readme = "README.md"
authors = [
    { name = "jinho-choi123", email = "choijinho817@gmail.com" }
]
requires-python = ">=3.13,<3.14"
dependencies = [
    "beartype>=0.22.9",
    "jaxtyping>=0.3.11",
    "torch==2.11.0",
]

[tool.uv.sources]
torch = [
    { index = "pytorch-cu129", marker = "sys_platform == 'linux'" },
]

[[tool.uv.index]]
name = "pytorch-cu129"
url = "https://download.pytorch.org/whl/cu129"
explicit = true

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
